// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculatePersonalFinance(arg1) {
  return window['go']['main']['App']['CalculatePersonalFinance'](arg1);
}

export function ShowErrorDialog(arg1) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1);
}
