// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculatePersonalFinance(arg1:number):Promise<main.FinanceResult>;

export function ShowErrorDialog(arg1:string):Promise<void>;
